UMSI-SI664-2018Fall/SI664-docs

- .gitignore
- install/win/win-choco_python_django-install.md
- install/win/win-mysql_mysqlclient-install.md
> Add Windows 10: Python, Django, MySQL Install Guide

- tools/mac-ngrok.md
- tools/win-ngrok.md
This PR adds a Windows version of the ngrok instructions and harmonizes the language between the Mac and Windows versions.
> Add Win instructions and harmonize language with Mac version.

- install/mac-brew_python_django_mysql-install.md
This PR adds the missing createsuperuser command.
> Add missing createsuperuser command

- install/mac-brew_python_django_mysql-install.md
> Wrong file reference; change .bash_profile to my.cnf

- install/mac-brew_python_django_mysql-install.md
Add code illustrating addition of symlinks
> Add view of /usr/local/mysql/lib after addition of sym links

- exercises/assignment_v4p2.md
- sql/mysql_statement_syntax.md
This PR adds assignment 4.2 as well as a skeletal MySQL statement syntax page.
> Add assignment 4.2

- README.md
This PR adds links to exercises.
> README: add Assignments section.

- README.md
- exercises/assignment_v4p2_win.md
This PR fixes a broken link and regularizes the file names.
> README: fix broken exercise link

- README.md
This PR fixes a broken TOC link
> Fix assignment broken link

- exercises/assignment_v4p2_win.md
> Replace $ cursor with > cursor in command line examples

- exercises/assignment_v4p2_mac.md
- exercises/assignment_v4p2_win.md
- exercises/assignment_v5p2.md
- install/mac-brew_python_django_mysql-install.md
This PR adds the mtg 5 assignment plus adds an over section to the mtg 4 assignment.
> Add assignment Mtg5, add overview to Mtg4 assignment

- exercises/assignment_v5p2.md
> Fix title, remove todo

- README.md
- exercises/assignment_v5p2.md
Fix Assignment 5 filename to submit; add link in README
> Fix Assignment 5 filename to submit; add link in README

- exercises/assignment_v5p2.md
Added the code and explanations for views and routes
> Update assignment_v5p2.md - adding views & routes

- README.md
- exercises/assignment_v5p2_mac.md
- exercises/assignment_v5p2_win.md
- misc/heritagesites_admin.py
This PR splits the Meeting 5 assignment into macOS and Windows versions.  Also adds:
* an overview
* instructions on adding a "Hello World" view
* instructions on adding routes
* link to a sample admin.py file
* updated instructions for using pip to install the mysqlclient library (Windows)
> Split Meeting 5 assignment into macOS and Windows versions

- exercises/assignment_v5p2_mac.md
> Fix bad title

- exercises/assignment_v5p2_mac.md
- exercises/assignment_v5p2_win.md
This PR fixes command line reference inconsistencies involving python . . . (Win) and python3 . . . (macOS).
> Fix command line python references

- exercises/assignment_v5p2_mac.md
- exercises/assignment_v5p2_win.md
Emphasize running the run_mysql_script.py file; add if disaster strikes section.
> Emphasize running the run_mysql_script.py file; add if disaster strikes section

- exercises/assignment_v5p2_mac.md
- exercises/assignment_v5p2_win.md
Add YAML int password warning to Windows doc; fix macOS warning.
> Add YAML int password warning

- README.md
- exercises/assignment_v6p2_mac.md
- exercises/assignment_v6p2_win.md
Add Mac and Win version of assignment 6.2
> Add Mac and Win version of assignment 6.2

- exercises/assignment_v6p2_mac.md
- exercises/assignment_v6p2_win.md
This PR moves the testing section to below templates section; also changes submission instructions to upload a zip file
> Move testing section below templates section; change submission instructions to upload a zip file

- exercises/assignment_v6p2_mac.md
- exercises/assignment_v6p2_win.md
> Escape \< & \> in titles

- exercises/assignment_v6p2_mac.md
- exercises/assignment_v6p2_win.md
> Fix bad escape char fixes.

- sql/mysql_select_examples.md
> Fix appendix A.2 heading size.

- sql/mysql_select_examples.md
> Fix sub-heading title typos

- orm/django_orm.md
- sql/mysql_select_examples.md
This PR adds a Django ORM review doc.
> Add Django ORM review doc

- orm/django_orm.md
- sql/mysql_select_examples.md
This PR adds further guidance on the use of COUNT(DISTINCT...)
> Add further guidance on the use of COUNT(DISTINCT...)

- orm/django_orm.md
> Add TOC, reorder-sections

- orm/django_orm.md
- sql/mysql_select_examples.md
This PR Add TOC to MySQL doc; renumber sections, plus add TOC header to ORM doc.
> Add TOC to MySQL doc; renumber sections, plus add TOC header to ORM doc

- orm/django_orm.md
This PR adds an ORM Count() example
> Add Count(value, distinct=True) example

- exams/si664_midterm-20181023.md
Tweek the view class property values
> Adjust context_object_name values

- exercises/assignment_v7p2.md
Add http://127.0.0.1:8000/auth/complete/google-oauth2/
> Add additional Google OAuth2 credential redirect URI

- install/mac-brew_python_django_mysql-install.md
Add the following examples:
```bash
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export MYSQL_HOME="/usr/local/mysql"
export PATH="$JAVA_HOME/bin:$PATH"
export PATH="$MYSQL_HOME/bin:$PATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
```
```bash
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export MYSQL_HOME="/usr/local/mysql"
export PATH="/usr/local/bin:/usr/local/sbin:$JAVA_HOME/bin:$MYSQL_HOME/bin:$PATH"
```
> Update PATH examples.

- github/github-mac.md
This PR addresses a bad doc link.
> Fix bad README doc link.

- github/github-mac.md
Adds missing section discussing minimal Git config settings.
> Add Create Git identity section

- README.md
- exams/si664_midterm_answers-20181023.md
Provide the answer key to the students.
> Add Midterm answers doc

- exercises/assignment_v8p2.md
Last record is Victoria Falls.
> Update reference to last heritage site record.

- exercises/assignment_v8p2.md
Add missing templatetags section.
> Add templatetags section

- exercises/assignment_v8p2.md
> Fix broken link

- exercises/assignment_v8p2.md
> Fix section 3.5 heading formatting.

- github/static/.gitignore
This PR adds `secrets.py` to the list of files to be ignored by Git.
> Ignore secrets.py

- README.md
> Fix README TOC

- exercises/assignment_v10p2.md
> Fix typo in zip file name

- exercises/assignment_v10p2.md
> Fix bad views.py link

- extra_credit/django_orm_queryset_1.md
> Add ORM extra credit. Northern European non-Roman settlement heritage sites.

- exercises/assignment_v10p2.md
- extra_credit/django_orm_queryset_1.md
> Fix typo in assignment 10.2; tweak extra credit text

- README.md
- exercises/assignment_v3p2.md
- exercises/assignment_v8p2.md
- exercises/assignment_v8p3.md
- exercises/assignment_v9p2.md
- exercises/assignment_v9p3.md
- exercises/final_project.md
This PR adds the final project doc.  It also updates a number of earlier assignment docs as well as adds assignments that were posted in Canvas.
> Add Final Project doc

- exercises/final_project.md
Fix bad links and wrong section numbering for the API section header.
> Fix broken internal links and bad section numbering.

- sql/mysql_create_database.md
This PR adds a Gotcha section to the create database from flat files doc.
> Add a gotchas section.

- exercises/final_project.md
Add example Meta class warning.
> Add Model Meta class managed=False warning
